quinnbank:
  environment:
    name: uat
    tier: controlled-non-production
    production: false

spring:
  datasource:
    url: ${QUINNBANK_UAT_DB_URL:${QUINNBANK_DB_URL}}
    username: ${QUINNBANK_UAT_DB_USERNAME:${QUINNBANK_DB_USERNAME}}
    password: ${QUINNBANK_UAT_DB_PASSWORD:${QUINNBANK_DB_PASSWORD}}

logging:
  level:
    com.quinnbank.core: INFO
