CREATE TABLE identity_user
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id    UUID         NOT NULL,
    owner_type   VARCHAR(50)  NOT NULL,
    owner_id     BIGINT       NOT NULL,
    username     VARCHAR(120) NOT NULL,
    email        VARCHAR(255),
    phone_number VARCHAR(50),
    status       VARCHAR(50)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_identity_user_public_id UNIQUE (public_id),
    CONSTRAINT uq_identity_user_username UNIQUE (username),
    CONSTRAINT uq_identity_user_email UNIQUE (email),
    CONSTRAINT uq_identity_user_phone_number UNIQUE (phone_number),
    CONSTRAINT ck_identity_user_owner_type CHECK (owner_type IN ('CUSTOMER', 'STAFF')),
    CONSTRAINT ck_identity_user_owner_id_positive CHECK (owner_id > 0),
    CONSTRAINT ck_identity_user_status
        CHECK (status IN ('PENDING_ACTIVATION', 'ACTIVE', 'LOCKED', 'DISABLED'))
);

CREATE INDEX ix_identity_user_owner ON identity_user (owner_type, owner_id);

CREATE TABLE identity_credential
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_user_id        BIGINT       NOT NULL,
    type                    VARCHAR(50)  NOT NULL,
    password_hash           VARCHAR(255) NOT NULL,
    password_changed_on_utc TIMESTAMP    NOT NULL,
    must_change_password    BOOLEAN      NOT NULL,
    created_on_utc          TIMESTAMP    NOT NULL,
    CONSTRAINT fk_identity_credential_user
        FOREIGN KEY (identity_user_id) REFERENCES identity_user (id),
    CONSTRAINT uq_identity_credential_user_type UNIQUE (identity_user_id, type),
    CONSTRAINT ck_identity_credential_type CHECK (type IN ('PASSWORD'))
);

CREATE TABLE identity_role
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(80) NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    CONSTRAINT uq_identity_role_code UNIQUE (code),
    CONSTRAINT ck_identity_role_code CHECK (code IN ('CUSTOMER', 'TELLER', 'ADMIN'))
);

CREATE TABLE identity_permission
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(120) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT uq_identity_permission_code UNIQUE (code),
    CONSTRAINT ck_identity_permission_code CHECK (
        code IN (
            'CUSTOMER_VIEW',
            'CUSTOMER_CREATE',
            'ACCOUNT_OPEN',
            'ACCOUNT_VIEW',
            'ACCOUNT_CLOSE',
            'IDENTITY_USER_CREATE',
            'IDENTITY_USER_VIEW',
            'IDENTITY_USER_STATUS_CHANGE',
            'IDENTITY_ROLE_ASSIGN'
        )
    )
);

CREATE TABLE identity_user_role
(
    identity_user_id BIGINT    NOT NULL,
    role_id          BIGINT    NOT NULL,
    assigned_at      TIMESTAMP NOT NULL,
    CONSTRAINT pk_identity_user_role PRIMARY KEY (identity_user_id, role_id),
    CONSTRAINT fk_identity_user_role_user
        FOREIGN KEY (identity_user_id) REFERENCES identity_user (id),
    CONSTRAINT fk_identity_user_role_role
        FOREIGN KEY (role_id) REFERENCES identity_role (id)
);

CREATE TABLE identity_role_permission
(
    role_id       BIGINT    NOT NULL,
    permission_id BIGINT    NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    CONSTRAINT pk_identity_role_permission PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_identity_role_permission_role
        FOREIGN KEY (role_id) REFERENCES identity_role (id),
    CONSTRAINT fk_identity_role_permission_permission
        FOREIGN KEY (permission_id) REFERENCES identity_permission (id)
);

INSERT INTO identity_role (code, created_at)
VALUES ('CUSTOMER', CURRENT_TIMESTAMP),
       ('TELLER', CURRENT_TIMESTAMP),
       ('ADMIN', CURRENT_TIMESTAMP);

INSERT INTO identity_permission (code, created_at)
VALUES ('CUSTOMER_VIEW', CURRENT_TIMESTAMP),
       ('CUSTOMER_CREATE', CURRENT_TIMESTAMP),
       ('ACCOUNT_OPEN', CURRENT_TIMESTAMP),
       ('ACCOUNT_VIEW', CURRENT_TIMESTAMP),
       ('ACCOUNT_CLOSE', CURRENT_TIMESTAMP),
       ('IDENTITY_USER_CREATE', CURRENT_TIMESTAMP),
       ('IDENTITY_USER_VIEW', CURRENT_TIMESTAMP),
       ('IDENTITY_USER_STATUS_CHANGE', CURRENT_TIMESTAMP),
       ('IDENTITY_ROLE_ASSIGN', CURRENT_TIMESTAMP);

INSERT INTO identity_role_permission (role_id, permission_id, created_at)
SELECT r.id, p.id, CURRENT_TIMESTAMP
FROM identity_role r
JOIN identity_permission p ON p.code = 'ACCOUNT_VIEW'
WHERE r.code = 'CUSTOMER';

INSERT INTO identity_role_permission (role_id, permission_id, created_at)
SELECT r.id, p.id, CURRENT_TIMESTAMP
FROM identity_role r
JOIN identity_permission p ON p.code IN ('CUSTOMER_VIEW', 'CUSTOMER_CREATE', 'ACCOUNT_OPEN', 'ACCOUNT_VIEW')
WHERE r.code = 'TELLER';

INSERT INTO identity_role_permission (role_id, permission_id, created_at)
SELECT r.id, p.id, CURRENT_TIMESTAMP
FROM identity_role r
CROSS JOIN identity_permission p
WHERE r.code = 'ADMIN';
